### PR TITLE
Add 'Visual Code Block' Markdown Syntax

### PR DESCRIPTION
**Pull request by Hamms**
Based on [CurriculumBuilder's Doclinks](https://github.com/code-dot-org/curriculumbuilder/blob/master/curriculumBuilder/doclinks.py), this markdown syntax is intended to be a way to format inline code so as to resemble a generic visual code block such as those created by Blockly and Droplet.

Will be used in conjunction with standard Markdown links.

image

Required for https://github.com/code-dot-org/code-dot-org/pull/39569

### CODE REVIEW

**Review by Hamms — COMMENTED** [review]
FYI reviewers; check out the README of this repo for links to useful information about remark plugins if you are unfamiliar

**Review by davidsbailey — APPROVED** [review]
Very cool!

**Comment by Hamms** [comment]
Isn't Remark neat??

**Comment by Hamms** [comment]
Hmm, hold up. Something's funky here; I updated the way the plugin generates HTML in https://github.com/code-dot-org/remark-plugins/pull/29/commits/bca013f5b379d3119d47579e867bb578de6754b5 but forgot to update the tests to match. But Travis is still giving me a green checkmark, so either it's not running the test suite or the test suite doesn't include the new test

**Comment by Hamms** [comment]
Ah, it was a naming problem; this project wants tests to be named `*.test.js`, mine was named `*Test.js`.

While fixing the tests, I was struck by just how gross it is to do so much styling inline for this. I decided that CSS would be a much better implementation.

**Comment by dmcavoy** [comment]
Cool to see the preview of this in a lesson!

**Review by bethanyaconnor — APPROVED** [review]
Looks good. Thanks for adding all the tests!

**Pull request merged**
